# =====================================================================
# Скрипт автоматического развертывания проекта SPPR_Analytics
# =====================================================================

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot

Write-Host "🚀 Создание структуры папок..." -ForegroundColor Cyan
New-Item -ItemType Directory -Path "$root\.vscode" -Force | Out-Null
New-Item -ItemType Directory -Path "$root\docs" -Force | Out-Null
New-Item -ItemType Directory -Path "$root\src" -Force | Out-Null

function Save-FileLines {
    param([string]$Path, [string[]]$Lines)
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    $content = $Lines -join "`r`n"
    [System.IO.File]::WriteAllText($Path, $content, $utf8NoBom)
    Write-Host "  -> Создан файл: $(Split-Path $Path -Leaf)" -ForegroundColor Green
}

# =====================================================================
# 1. ДОКУМЕНТАЦИЯ (docs/)
# =====================================================================

Save-FileLines -Path "$root\docs\SPEC.md" -Lines @(
    "# SPEC.md: Аналитика и аудит обращений 1С (VBA + Gemini API)",
    "",
    "## 1. Цель проекта",
    "Автономный аудит обращений службы технической поддержки 1С (СППР): пакетная классификация и оценка качества решений через Gemini API, расчет бизнес-метрик (SLA), ведение системных логов и генерация интерактивного HTML-презентационного отчета без сторонних облачных сред.",
    "",
    "## 2. Стек и окружение",
    "* **Среда исполнения:** Microsoft Excel (VBA 7.x, 32/64-bit).",
    "* **Среда разработки:** VS Code + синхронизатор vba_sync.ps1.",
    "* **Сетевые вызовы:** MSXML2.ServerXMLHTTP.6.0.",
    "* **Кодировки и потоки:** ADODB.Stream (UTF-8).",
    "* **Модели ИИ:**",
    "  * Пакетная разметка (Batching): gemini-2.5-flash",
    "  * Выводы архитектора (Root Cause): gemini-2.5-pro",
    "",
    "## 3. Функциональные требования",
    "1. **Загрузка и валидация данных:** Чтение листа Data, фильтрация по заполненной дате cls.",
    "2. **Расчет SLA:** Подсчет рабочих часов (WORK_HOURS = 8) без учета выходных.",
    "3. **Батчинг:** Пачки по 40 тикетов, вызов Gemini API с response_schema.",
    "4. **Root Cause:** Генерация выводов архитектора через модель Pro.",
    "5. **Логирование:** Листы Logs и Token в книге Excel.",
    "6. **Экспорт отчета:** Рендеринг HTML в UTF-8 на базе template.html."
)

Save-FileLines -Path "$root\docs\DATA.md" -Lines @(
    "# DATA.md: Схема и контракты данных",
    "",
    "## 1. Входные данные (Лист 'Data' в Excel)",
    "| Колонка | Имя поля | Тип | Описание |",
    "| :--- | :--- | :--- | :--- |",
    "| A | id | String | Номер обращения |",
    "| B | reg | DateTime | Дата регистрации |",
    "| C | cls | DateTime | Дата закрытия |",
    "| D | cli | String | Инициатор |",
    "| E | anl | String | Аналитик |",
    "| F | sec | String | Тема / Раздел |",
    "| G | desc | String | Описание |",
    "| H | sol | String | Решение |",
    "",
    "## 2. Листы книги Excel",
    "* **Logs:** Run_ID, Timestamp, Year, Week, Total_Tickets, Status.",
    "* **Token:** Run_ID, Batch_Model, Batch_Tokens, Summary_Model, Summary_Tokens."
)

Save-FileLines -Path "$root\docs\SESSION_LOG.md" -Lines @(
    "# SESSION_LOG.md: Журнал разработки и изменений",
    "",
    "## [Текущий статус]",
    "* **Этап:** Миграция с Colab на чистый Excel VBA.",
    "* **Статус:** Модули развернуты в каталоге src/.",
    "",
    "## [Unreleased]",
    "### Added",
    "- Документация SPEC.md, DATA.md, SESSION_LOG.md.",
    "- Модули VBA: Mod_Config_And_Types, Mod_JSON_Utils, Mod_Gemini_API, Mod_Analytics, Mod_Report_Generator, Mod_Main.",
    "- Скрипт синхронизации vba_sync.ps1 и .vscode/tasks.json."
)

# =====================================================================
# 2. КОНФИГУРАЦИЯ VS CODE (.vscode/tasks.json)
# =====================================================================

Save-FileLines -Path "$root\.vscode\tasks.json" -Lines @(
    '{',
    '    "version": "2.0.0",',
    '    "tasks": [',
    '        {',
    '            "label": "VBA: Import to Excel (Собрать в Workbook.xlsm)",',
    '            "type": "shell",',
    '            "command": "powershell.exe",',
    '            "args": [',
    '                "-ExecutionPolicy", "Bypass",',
    '                "-File", "${workspaceFolder}/vba_sync.ps1",',
    '                "-Action", "import"',
    '            ],',
    '            "group": {',
    '                "kind": "build",',
    '                "isDefault": true',
    '            },',
    '            "problemMatcher": []',
    '        },',
    '        {',
    '            "label": "VBA: Export from Excel (Выгрузить в src/)",',
    '            "type": "shell",',
    '            "command": "powershell.exe",',
    '            "args": [',
    '                "-ExecutionPolicy", "Bypass",',
    '                "-File", "${workspaceFolder}/vba_sync.ps1",',
    '                "-Action", "export"',
    '            ],',
    '            "group": "build",',
    '            "problemMatcher": []',
    '        }',
    '    ]',
    '}'
)

# =====================================================================
# 3. СКРИПТ СИНХРОНИЗАЦИИ (vba_sync.ps1)
# =====================================================================

Save-FileLines -Path "$root\vba_sync.ps1" -Lines @(
    'param (',
    '    [Parameter(Mandatory=$true)]',
    '    [ValidateSet("export", "import")]',
    '    [string]$Action,',
    '    [string]$WorkbookPath = "$PSScriptRoot\Workbook.xlsm",',
    '    [string]$SourceDir = "$PSScriptRoot\src"',
    ')',
    'if (-not (Test-Path $SourceDir)) { New-Item -ItemType Directory -Path $SourceDir | Out-Null }',
    '$excel = New-Object -ComObject Excel.Application',
    '$excel.Visible = $false',
    '$excel.DisplayAlerts = $false',
    'try {',
    '    if (-not (Test-Path $WorkbookPath)) {',
    '        Write-Host "Создание новой книги $WorkbookPath..." -ForegroundColor Yellow',
    '        $wb = $excel.Workbooks.Add()',
    '        $wb.SaveAs($WorkbookPath, 52)',
    '    } else {',
    '        $wb = $excel.Workbooks.Open($WorkbookPath)',
    '    }',
    '    $vbProj = $wb.VBProject',
    '    if ($Action -eq "export") {',
    '        Write-Host "📥 Экспорт модулей из Excel в $SourceDir..." -ForegroundColor Cyan',
    '        foreach ($comp in $vbProj.VBComponents) {',
    '            $ext = switch ($comp.Type) { 1 { ".bas" } 2 { ".cls" } 3 { ".frm" } default { $null } }',
    '            if ($ext) {',
    '                $targetFile = Join-Path $SourceDir ($comp.Name + $ext)',
    '                $comp.Export($targetFile)',
    '                Write-Host "  -> Экспортирован: $($comp.Name)$ext"',
    '            }',
    '        }',
    '        Write-Host "✅ Экспорт завершен!" -ForegroundColor Green',
    '    }',
    '    elseif ($Action -eq "import") {',
    '        Write-Host "📤 Импорт кода из $SourceDir в Excel..." -ForegroundColor Cyan',
    '        $files = Get-ChildItem -Path $SourceDir -Include *.bas, *.cls, *.frm -File',
    '        foreach ($file in $files) {',
    '            $modName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)',
    '            $existing = $null',
    '            try { $existing = $vbProj.VBComponents.Item($modName) } catch {}',
    '            if ($existing -and $existing.Type -in @(1, 2, 3)) {',
    '                $vbProj.VBComponents.Remove($existing)',
    '            }',
    '            $vbProj.VBComponents.Import($file.FullName) | Out-Null',
    '            Write-Host "  <- Импортирован: $($file.Name)"',
    '        }',
    '        $wb.Save()',
    '        Write-Host "✅ Импорт завершен, книга сохранена!" -ForegroundColor Green',
    '    }',
    '}',
    'catch {',
    '    Write-Error "Ошибка синхронизации: $_"',
    '}',
    'finally {',
    '    if ($wb) { $wb.Close($false) }',
    '    $excel.Quit()',
    '    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null',
    '    [System.GC]::Collect()',
    '    [System.GC]::WaitForPendingFinalizers()',
    '}'
)

# =====================================================================
# 4. ШАБЛОН ОТЧЕТА (template.html)
# =====================================================================

Save-FileLines -Path "$root\template.html" -Lines @(
    '<!DOCTYPE html>',
    '<html lang="ru">',
    '<head>',
    '    <meta charset="UTF-8">',
    '    <title>Аналитика обращений в 1С Корпоративная поддержка</title>',
    '    <style>',
    '        * { margin: 0; padding: 0; box-sizing: border-box; }',
    '        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; background: #f0f2f5; color: #1a1a2e; }',
    '        .presentation-container { max-width: 1400px; margin: 0 auto; padding: 20px; }',
    '        .nav-bar { display: flex; justify-content: space-between; align-items: center; background: #ffffff; padding: 12px 24px; border-radius: 12px; margin-bottom: 24px; }',
    '        .nav-bar .title { font-size: 18px; font-weight: 600; }',
    '        .nav-controls { display: flex; align-items: center; gap: 12px; }',
    '        .nav-controls button { background: #e8ecf1; border: none; padding: 8px 18px; border-radius: 8px; font-size: 14px; cursor: pointer; }',
    '        .nav-controls button.primary { background: #1a73e8; color: #fff; }',
    '        .slide { display: none; background: #ffffff; border-radius: 16px; padding: 32px 36px; min-height: 500px; }',
    '        .slide.active { display: block; }',
    '        .slide-title { font-size: 26px; font-weight: 700; margin-bottom: 20px; border-bottom: 3px solid #1a73e8; padding-bottom: 8px; }',
    '        .slide-subtitle { font-size: 16px; font-weight: 600; margin: 16px 0 8px 0; color: #2c3e50; }',
    '        .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }',
    '        .grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; }',
    '        .stat-card { background: #f8f9fc; border-radius: 12px; padding: 16px; border-left: 4px solid #1a73e8; }',
    '        .stat-card .label { font-size: 12px; color: #5f6b7a; text-transform: uppercase; }',
    '        .stat-card .value { font-size: 24px; font-weight: 700; margin-top: 4px; }',
    '        .stat-card.green { border-left-color: #34a853; }',
    '        .stat-card.orange { border-left-color: #fbbc04; }',
    '        .stat-card.purple { border-left-color: #7c3aed; }',
    '        .table-wrap { overflow-x: auto; margin-top: 10px; }',
    '        table { width: 100%; border-collapse: collapse; font-size: 13px; }',
    '        table th { background: #f1f3f5; padding: 8px 12px; text-align: left; border-bottom: 2px solid #d0d5dd; }',
    '        table td { padding: 8px 12px; border-bottom: 1px solid #e8ecf1; }',
    '        .badge { display: inline-block; padding: 2px 10px; border-radius: 10px; font-size: 11px; font-weight: 600; }',
    '        .badge.excellent { background: #d4edda; color: #155724; }',
    '        .badge.good { background: #cce5ff; color: #004085; }',
    '        .badge.bad { background: #f8d7da; color: #721c24; }',
    '        .badge.orange { background: #fff3cd; color: #856404; }',
    '        .ticket-list { font-size: 12px; color: #3d4a5c; }',
    '    </style>',
    '</head>',
    '<body>',
    '<div class="presentation-container">',
    '    <div class="nav-bar">',
    '        <span class="title">📊 1С Поддержка · Аналитика</span>',
    '        <div class="nav-controls">',
    '            <button onclick="goSlide(-1)">◀ Назад</button>',
    '            <span id="slideCounter">1 / 9</span>',
    '            <button onclick="goSlide(1)" class="primary">Вперед ▶</button>',
    '        </div>',
    '    </div>',
    '    <!-- СЛАЙД 1 -->',
    '    <div class="slide active" data-slide="1">',
    '        <h2 class="slide-title">📈 Общая статистика {{ week_header }}</h2>',
    '        <div class="grid-2">',
    '            <div>',
    '                <div class="grid-3">',
    '                    <div class="stat-card"><div class="label">Всего</div><div class="value">{{ total_tickets }}</div></div>',
    '                    <div class="stat-card green"><div class="label">Медиана (ч)</div><div class="value">{{ med_hour }}</div></div>',
    '                    <div class="stat-card orange"><div class="label">Среднее (ч)</div><div class="value">{{ mid_hour }}</div></div>',
    '                </div>',
    '                <div style="margin-top:14px;"><div class="label">Регистрация:</div><div>{{ dates_reg }}</div></div>',
    '                <div style="margin-top:6px;"><div class="label">Закрытие:</div><div>{{ dates_cls }}</div></div>',
    '                <div style="margin-top:14px;"><svg id="pieChart" width="200" height="200" viewBox="0 0 200 200"></svg></div>',
    '            </div>',
    '            <div>',
    '                <div class="slide-subtitle">👤 Топ-5 инициаторов</div>',
    '                <div class="table-wrap"><table><thead><tr><th>Инициатор</th><th>Кол-во</th><th>Тематики</th><th>Тикеты</th></tr></thead>',
    '                <tbody>{% for row in top_initiators %}{% endfor %}</tbody></table></div>',
    '            </div>',
    '        </div>',
    '    </div>',
    '    <!-- СЛАЙД 2 -->',
    '    <div class="slide" data-slide="2">',
    '        <h2 class="slide-title">😐 Эмоциональный фон обращений</h2>',
    '        <div class="grid-3" style="margin-bottom:16px;">',
    '            <div class="stat-card"><div class="label">С эмоциями</div><div class="value">{{ emo_total }}</div></div>',
    '            <div class="stat-card orange"><div class="label">Ср. балл</div><div class="value">{{ emo_avg }}</div></div>',
    '            <div class="stat-card purple"><div class="label">Макс. балл</div><div class="value">{{ emo_max }}</div></div>',
    '        </div>',
    '        <div class="table-wrap"><table><thead><tr><th>№</th><th>Балл</th><th>Инициатор</th><th>Текст</th><th>Аргументация</th></tr></thead>',
    '        <tbody>{% for row in emo_tickets %}{% endfor %}</tbody></table></div>',
    '    </div>',
    '    <!-- СЛАЙД 3 -->',
    '    <div class="slide" data-slide="3">',
    '        <h2 class="slide-title">⚠️ Массовые проблемы и тренды</h2>',
    '        <div class="slide-subtitle">🏷️ Топ-5 проблем</div>',
    '        <div class="table-wrap"><table><thead><tr><th>Сбой</th><th>Кол-во</th><th>Тикеты</th><th>Качество</th></tr></thead>',
    '        <tbody>{% for row in top_topics %}{% endfor %}</tbody></table></div>',
    '        <div class="slide-subtitle" style="margin-top:16px;">⏳ Критические инциденты</div>',
    '        <div>{% for row in crit_tickets %}{% endfor %}</div>',
    '    </div>',
    '    <!-- СЛАЙД 4 -->',
    '    <div class="slide" data-slide="4">',
    '        <h2 class="slide-title">🤖 Альтернативное мнение ИИ (Всего: {{ alt_total }})</h2>',
    '        <div class="table-wrap"><table><thead><tr><th>№</th><th>Тема</th><th>Описание</th><th>Решение</th><th>Мнение ИИ</th></tr></thead>',
    '        <tbody>{% for row in alt_tickets %}{% endfor %}</tbody></table></div>',
    '    </div>',
    '    <!-- СЛАЙД 5 -->',
    '    <div class="slide" data-slide="5">',
    '        <h2 class="slide-title">🏆 Топ-10 рейтинг аналитиков</h2>',
    '        <div class="table-wrap"><table><thead><tr><th>Аналитик</th><th>Всего</th><th>⭐ Отл</th><th>✅ Хор</th><th>❌ Плох</th><th>Сложность</th><th>Балл</th></tr></thead>',
    '        <tbody>{% for row in top_analysts %}{% endfor %}</tbody></table></div>',
    '    </div>',
    '    <!-- СЛАЙД 6 -->',
    '    <div class="slide" data-slide="6">',
    '        <h2 class="slide-title">🔴 Оценка «Плохо»</h2>',
    '        <div>{% for row in bad_tickets %}{% endfor %}</div>',
    '    </div>',
    '    <!-- СЛАЙД 7 -->',
    '    <div class="slide" data-slide="7">',
    '        <h2 class="slide-title">🌟 Оценка «Отлично»</h2>',
    '        <div>{% for row in exc_tickets %}{% endfor %}</div>',
    '    </div>',
    '    <!-- СЛАЙД 8 -->',
    '    <div class="slide" data-slide="8">',
    '        <h2 class="slide-title">📌 Заключение и выводы Архитектора</h2>',
    '        <ul style="list-style:disc;padding-left:20px;line-height:1.8;">{{ ai_conclusions | safe }}</ul>',
    '        <div style="margin-top:16px;padding:12px;background:#f0f7ff;border-radius:8px;font-weight:600;color:#1a73e8;">💡 {{ tip_text }}</div>',
    '    </div>',
    '    <!-- СЛАЙД 9 -->',
    '    <div class="slide" data-slide="9">',
    '        <h2 class="slide-title">🏅 Номинации и Токены</h2>',
    '        <div class="grid-2">',
    '            <div>',
    '                <div class="slide-subtitle">🏆 Номинации</div>',
    '                <div><b>Сложность:</b> {{ nom_hard_anl }} ({{ nom_hard_txt }})</div>',
    '                <div><b>Количество:</b> {{ nom_qty_anl }} ({{ nom_qty_txt }})</div>',
    '                <div><b>Качество:</b> {{ nom_qual_anl }} ({{ nom_qual_txt }})</div>',
    '            </div>',
    '            <div>',
    '                <div class="slide-subtitle">⚙️ Токены</div>',
    '                <div><b>{{ batch_model }}:</b> {{ batch_tokens }} токенов</div>',
    '                <div><b>{{ summary_model }}:</b> {{ summary_tokens }} токенов</div>',
    '            </div>',
    '        </div>',
    '    </div>',
    '</div>',
    '<script>',
    '    let currentSlide = 1, totalSlides = 9;',
    '    function updateSlide() {',
    '        document.querySelectorAll(".slide").forEach((el, idx) => el.classList.toggle("active", (idx + 1) === currentSlide));',
    '        document.getElementById("slideCounter").textContent = currentSlide + " / " + totalSlides;',
    '    }',
    '    function goSlide(dir) {',
    '        let n = currentSlide + dir;',
    '        if (n >= 1 && n <= totalSlides) { currentSlide = n; updateSlide(); }',
    '    }',
    '    document.addEventListener("keydown", (e) => {',
    '        if (e.key === "ArrowRight" || e.key === " ") { e.preventDefault(); goSlide(1); }',
    '        if (e.key === "ArrowLeft") { e.preventDefault(); goSlide(-1); }',
    '    });',
    '    function drawPieChart() {',
    '        const data = {{ pie_json | safe }};',
    '        const colors = ["#1a73e8", "#34a853", "#fbbc04", "#ea4335", "#7c3aed", "#00bcd4", "#ff6b6b"];',
    '        const svg = document.getElementById("pieChart");',
    '        if(!svg || !data) return;',
    '        const cx = 100, cy = 100, r = 80;',
    '        let total = Object.values(data).reduce((a, b) => a + b, 0);',
    '        let startAngle = -Math.PI / 2, i = 0;',
    '        while (svg.firstChild) svg.removeChild(svg.firstChild);',
    '        for (const [label, count] of Object.entries(data)) {',
    '            const angle = (count / total) * 2 * Math.PI;',
    '            const endAngle = startAngle + angle;',
    '            const x1 = cx + r * Math.cos(startAngle), y1 = cy + r * Math.sin(startAngle);',
    '            const x2 = cx + r * Math.cos(endAngle), y2 = cy + r * Math.sin(endAngle);',
    '            const largeArc = angle > Math.PI ? 1 : 0;',
    '            const path = document.createElementNS("http://www.w3.org/2000/svg", "path");',
    '            path.setAttribute("d", `M ${cx} ${cy} L ${x1} ${y1} A ${r} ${r} 0 ${largeArc} 1 ${x2} ${y2} Z`);',
    '            path.setAttribute("fill", colors[i % colors.length]);',
    '            svg.appendChild(path);',
    '            startAngle = endAngle; i++;',
    '        }',
    '        const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");',
    '        circle.setAttribute("cx", cx); circle.setAttribute("cy", cy); circle.setAttribute("r", "40"); circle.setAttribute("fill", "#fff");',
    '        svg.appendChild(circle);',
    '        const text = document.createElementNS("http://www.w3.org/2000/svg", "text");',
    '        text.setAttribute("x", cx); text.setAttribute("y", cy + 5); text.setAttribute("text-anchor", "middle"); text.setAttribute("font-weight", "bold");',
    '        text.textContent = total; svg.appendChild(text);',
    '    }',
    '    document.addEventListener("DOMContentLoaded", drawPieChart);',
    '</script>',
    '</body>',
    '</html>'
)

# =====================================================================
# 5. МОДУЛИ VBA (src/)
# =====================================================================

Save-FileLines -Path "$root\src\Mod_Config_And_Types.bas" -Lines @(
    'Attribute VB_Name = "Mod_Config_And_Types"',
    'Option Explicit',
    '',
    'Public Const GEMINI_API_KEY As String = "ВАШ_GEMINI_API_KEY"',
    'Public Const BATCH_MODEL As String = "gemini-2.5-flash"',
    'Public Const SUMMARY_MODEL As String = "gemini-2.5-pro"',
    'Public Const BATCH_SIZE As Long = 40',
    'Public Const WORK_HOURS As Double = 8#',
    '',
    'Public Const TOP_INITIATORS_N As Long = 5',
    'Public Const TOP_LONGEST_N As Long = 10',
    'Public Const TOP_PROBLEMS_N As Long = 5',
    '',
    'Public Type TicketData',
    '    id As String',
    '    reg As String',
    '    cls As String',
    '    cli As String',
    '    anl As String',
    '    sec As String',
    '    desc As String',
    '    sol As String',
    '    reg_dt As Date',
    '    cls_dt As Date',
    '    has_cls As Boolean',
    '    iso_year As Long',
    '    iso_week As Long',
    '    dif_Hour As Double',
    '    topic_cluster As String',
    '    tone_deviation_score As Long',
    '    is_emotional As Boolean',
    '    emotion_argument As String',
    '    complexity As Long',
    '    initial_grade As String',
    '    final_grade As String',
    '    grade_argument As String',
    '    is_alternative As Boolean',
    '    is_critical_incident As Boolean',
    'End Type',
    '',
    'Public Function GetSystemInstruction() As String',
    '    Dim p As String',
    '    p = "Вы — ведущий системный аналитик 1С. Проведите аудит пакета обращений." & vbCrLf & _',
    '        "1. topic_cluster: конкретная суть сбоя/операции (без абстракций)." & vbCrLf & _',
    '        "2. final_grade: ПЛОХО, ХОРОШО, ОТЛИЧНО." & vbCrLf & _',
    '        "3. tone_deviation_score: от 0 (деловой) до 3 (оскорбления)." & vbCrLf & _',
    '        "4. complexity: 1-5. is_alternative: true/false. is_critical_incident: true/false."',
    '    GetSystemInstruction = p',
    'End Function'
)

Save-FileLines -Path "$root\src\Mod_JSON_Utils.bas" -Lines @(
    'Attribute VB_Name = "Mod_JSON_Utils"',
    'Option Explicit',
    '',
    'Public Function EscapeJSON(ByVal txt As String) As String',
    '    txt = Replace(txt, "\", "\\")',
    '    txt = Replace(txt, """", "\""")',
    '    txt = Replace(txt, vbCrLf, "\n")',
    '    txt = Replace(txt, vbCr, "\n")',
    '    txt = Replace(txt, vbLf, "\n")',
    '    txt = Replace(txt, vbTab, "\t")',
    '    EscapeJSON = txt',
    'End Function',
    '',
    'Public Function ExtractJSONValue(ByVal json As String, ByVal key As String) As String',
    '    Dim reg As Object, matches As Object',
    '    Set reg = CreateObject("VBScript.RegExp")',
    '    reg.Global = False',
    '    reg.IgnoreCase = True',
    '    reg.Pattern = """" & key & """\s*:\s*(""([^""\\]*(\\.[^""\\]*)*)""|([0-9\.\-]+)|(true|false|null))"',
    '    If reg.Test(json) Then',
    '        Set matches = reg.Execute(json)',
    '        Dim val As String: val = matches(0).SubMatches(0)',
    '        If Left(val, 1) = """" And Right(val, 1) = """" Then',
    '            val = Mid(val, 2, Len(val) - 2)',
    '            val = Replace(val, "\""", """")',
    '            val = Replace(val, "\n", vbCrLf)',
    '            val = Replace(val, "\\", "\")',
    '        End If',
    '        ExtractJSONValue = val',
    '    Else',
    '        ExtractJSONValue = ""',
    '    End If',
    'End Function',
    '',
    'Public Function ExtractArrayObjects(ByVal json As String, ByVal arrayName As String) As Collection',
    '    Dim col As New Collection, pStart As Long',
    '    pStart = InStr(1, json, """" & arrayName & """", vbTextCompare)',
    '    If pStart = 0 Then Set ExtractArrayObjects = col: Exit Function',
    '    pStart = InStr(pStart, json, "[")',
    '    If pStart = 0 Then Exit Function',
    '    Dim i As Long, depth As Long, objStart As Long, inQuotes As Boolean, ch As String',
    '    depth = 0: objStart = 0: inQuotes = False',
    '    For i = pStart To Len(json)',
    '        ch = Mid(json, i, 1)',
    '        If ch = """" And Mid(json, i - 1, 1) <> "\" Then',
    '            inQuotes = Not inQuotes',
    '        ElseIf Not inQuotes Then',
    '            If ch = "{" Then',
    '                If depth = 0 Then objStart = i',
    '                depth = depth + 1',
    '            ElseIf ch = "}" Then',
    '                depth = depth - 1',
    '                If depth = 0 And objStart > 0 Then',
    '                    col.Add Mid(json, objStart, i - objStart + 1)',
    '                    objStart = 0',
    '                End If',
    '            ElseIf ch = "]" And depth = 0 Then',
    '                Exit For',
    '            End If',
    '        End If',
    '    Next i',
    '    Set ExtractArrayObjects = col',
    'End Function'
)

Save-FileLines -Path "$root\src\Mod_Gemini_API.bas" -Lines @(
    'Attribute VB_Name = "Mod_Gemini_API"',
    'Option Explicit',
    '',
    'Public Function CallGeminiBatch(ByVal promptText As String, ByRef outPromptTok As Long, ByRef outCandTok As Long, ByRef outTotalTok As Long) As String',
    '    Dim http As Object: Set http = CreateObject("MSXML2.ServerXMLHTTP.6.0")',
    '    Dim url As String: url = "https://generativelanguage.googleapis.com/v1beta/models/" & BATCH_MODEL & ":generateContent?key=" & GEMINI_API_KEY',
    '    Dim schemaJson As String',
    '    schemaJson = "{""type"":""OBJECT"",""properties"":{""results"":{""type"":""ARRAY"",""items"":{""type"":""OBJECT"",""properties"":{" & _',
    '                 """id"":{""type"":""STRING""},""topic_cluster"":{""type"":""STRING""},""tone_deviation_score"":{""type"":""INTEGER""}," & _',
    '                 """is_emotional"":{""type"":""BOOLEAN""},""emotion_argument"":{""type"":""STRING""},""complexity"":{""type"":""INTEGER""}," & _',
    '                 """initial_grade"":{""type"":""STRING""},""final_grade"":{""type"":""STRING""},""grade_argument"":{""type"":""STRING""}," & _',
    '                 """is_alternative"":{""type"":""BOOLEAN""},""is_critical_incident"":{""type"":""BOOLEAN""}" & _',
    '                 "},""required"":[""id"",""topic_cluster"",""tone_deviation_score"",""is_emotional"",""emotion_argument"",""complexity"",""initial_grade"",""final_grade"",""grade_argument"",""is_alternative"",""is_critical_incident""]}}}}"',
    '    Dim body As String',
    '    body = "{""contents"":[{""parts"":[{""text"":""" & EscapeJSON(promptText) & """}]}]," & _',
    '           """systemInstruction"":{""parts"":[{""text"":""" & EscapeJSON(GetSystemInstruction()) & """}]}]," & _',
    '           """generationConfig"":{""responseMimeType"":""application/json"",""responseSchema"":" & schemaJson & ",""temperature"":0.1}}"',
    '    http.Open "POST", url, False',
    '    http.setRequestHeader "Content-Type", "application/json; charset=utf-8"',
    '    http.send body',
    '    If http.Status = 200 Then',
    '        Dim respText As String: respText = http.responseText',
    '        outPromptTok = CLng(Val(ExtractJSONValue(respText, "promptTokenCount")))',
    '        outCandTok = CLng(Val(ExtractJSONValue(respText, "candidatesTokenCount")))',
    '        outTotalTok = CLng(Val(ExtractJSONValue(respText, "totalTokenCount")))',
    '        CallGeminiBatch = ExtractJSONValue(respText, "text")',
    '    Else',
    '        Err.Raise vbObjectError + 500, "CallGeminiBatch", "API Error " & http.Status & ": " & http.responseText',
    '    End If',
    'End Function',
    '',
    'Public Function CallGeminiSummary(ByVal summaryPrompt As String, ByRef outTotalTok As Long) As String',
    '    Dim http As Object: Set http = CreateObject("MSXML2.ServerXMLHTTP.6.0")',
    '    Dim url As String: url = "https://generativelanguage.googleapis.com/v1beta/models/" & SUMMARY_MODEL & ":generateContent?key=" & GEMINI_API_KEY',
    '    Dim fullPrompt As String',
    '    fullPrompt = "Ты — главный архитектор систем 1С. Дай 3 вывода Root Cause: " & summaryPrompt & ". Формат HTML <li>"',
    '    Dim body As String',
    '    body = "{""contents"":[{""parts"":[{""text"":""" & EscapeJSON(fullPrompt) & """}]}],""generationConfig"":{""temperature"":0.2}}"',
    '    http.Open "POST", url, False',
    '    http.setRequestHeader "Content-Type", "application/json; charset=utf-8"',
    '    http.send body',
    '    If http.Status = 200 Then',
    '        Dim respText As String: respText = http.responseText',
    '        outTotalTok = CLng(Val(ExtractJSONValue(respText, "totalTokenCount")))',
    '        Dim res As String: res = ExtractJSONValue(respText, "text")',
    '        res = Replace(Replace(res, "```html", ""), "```", "")',
    '        CallGeminiSummary = Trim(res)',
    '    Else',
    '        CallGeminiSummary = "<li>Ошибка генерации выводов: " & http.Status & "</li>"',
    '    End If',
    'End Function'
)

Save-FileLines -Path "$root\src\Mod_Analytics.bas" -Lines @(
    'Attribute VB_Name = "Mod_Analytics"',
    'Option Explicit',
    '',
    'Public Function GetISOWeek(ByVal d As Date) As Long',
    '    GetISOWeek = DatePart("ww", d, vbMonday, vbFirstFourDays)',
    'End Function',
    '',
    'Public Function GetISOYear(ByVal d As Date) As Long',
    '    Dim w As Long, y As Long: w = DatePart("ww", d, vbMonday, vbFirstFourDays): y = Year(d)',
    '    If Month(d) = 1 And w >= 52 Then GetISOYear = y - 1 ElseIf Month(d) = 12 And w = 1 Then GetISOYear = y + 1 Else GetISOYear = y',
    'End Function',
    '',
    'Public Function CalcBusHours(ByVal dtStart As Date, ByVal dtEnd As Date) As Double',
    '    Dim d1 As Date, d2 As Date: d1 = DateValue(dtStart): d2 = DateValue(dtEnd)',
    '    If d1 > d2 Then CalcBusHours = 0#: Exit Function',
    '    Dim busDays As Long: busDays = Application.WorksheetFunction.NetworkDays(d1, d2) - 1',
    '    If busDays < 0 Then busDays = 0',
    '    CalcBusHours = busDays * WORK_HOURS',
    'End Function',
    '',
    'Public Function CalcMedian(ByRef arr() As Double, ByVal count As Long) As Double',
    '    If count = 0 Then CalcMedian = 0#: Exit Function',
    '    Dim i As Long, j As Long, temp As Double',
    '    For i = 1 To count - 1',
    '        For j = i + 1 To count',
    '            If arr(i) > arr(j) Then temp = arr(i): arr(i) = arr(j): arr(j) = temp',
    '        Next j',
    '    Next i',
    '    If count Mod 2 = 1 Then CalcMedian = arr((count + 1) \ 2) Else CalcMedian = (arr(count \ 2) + arr((count \ 2) + 1)) / 2#',
    'End Function'
)

Save-FileLines -Path "$root\src\Mod_Report_Generator.bas" -Lines @(
    'Attribute VB_Name = "Mod_Report_Generator"',
    'Option Explicit',
    '',
    'Public Sub GenerateHtmlReport( _',
    '    ByVal templatePath As String, ByVal outputPath As String, _',
    '    ByRef tickets() As TicketData, ByVal totalCount As Long, _',
    '    ByVal maxYear As Long, ByVal maxWeek As Long, _',
    '    ByVal minRegStr As String, ByVal maxRegStr As String, _',
    '    ByVal minClsStr As String, ByVal maxClsStr As String, _',
    '    ByVal medHour As Double, ByVal midHour As Double, _',
    '    ByVal aiConclusions As String, _',
    '    ByVal batchTokens As Long, ByVal summaryTokens As Long _',
    ')',
    '    Dim fso As Object, stm As Object',
    '    Set fso = CreateObject("Scripting.FileSystemObject")',
    '    If Not fso.FileExists(templatePath) Then Err.Raise vbObjectError + 404, "ReportGen", "Шаблон не найден: " & templatePath',
    '    Set stm = CreateObject("ADODB.Stream")',
    '    stm.Type = 2: stm.Charset = "utf-8": stm.Open: stm.LoadFromFile templatePath',
    '    Dim tpl As String: tpl = stm.ReadText(-1): stm.Close',
    '    Dim emoTotal As Long, emoSum As Long, emoMax As Long, altTotal As Long, i As Long',
    '    Dim topicCounts As Object: Set topicCounts = CreateObject("Scripting.Dictionary")',
    '    Dim initiatorCounts As Object: Set initiatorCounts = CreateObject("Scripting.Dictionary")',
    '    Dim initiatorTopics As Object: Set initiatorTopics = CreateObject("Scripting.Dictionary")',
    '    Dim anlTotal As Object: Set anlTotal = CreateObject("Scripting.Dictionary")',
    '    Dim anlExc As Object: Set anlExc = CreateObject("Scripting.Dictionary")',
    '    Dim anlGood As Object: Set anlGood = CreateObject("Scripting.Dictionary")',
    '    Dim anlBad As Object: Set anlBad = CreateObject("Scripting.Dictionary")',
    '    Dim anlCompSum As Object: Set anlCompSum = CreateObject("Scripting.Dictionary")',
    '    For i = 1 To totalCount',
    '        If tickets(i).tone_deviation_score > 0 Then',
    '            emoTotal = emoTotal + 1: emoSum = emoSum + tickets(i).tone_deviation_score',
    '            If tickets(i).tone_deviation_score > emoMax Then emoMax = tickets(i).tone_deviation_score',
    '        End If',
    '        If tickets(i).is_alternative Then altTotal = altTotal + 1',
    '        Dim cl As String: cl = tickets(i).topic_cluster',
    '        If cl <> "" Then topicCounts(cl) = topicCounts(cl) + 1',
    '        Dim cli As String: cli = tickets(i).cli',
    '        If cli <> "" Then initiatorCounts(cli) = initiatorCounts(cli) + 1: initiatorTopics(cli) = initiatorTopics(cli) & IIf(initiatorTopics(cli) = "", "", ", ") & cl',
    '        Dim anl As String: anl = tickets(i).anl',
    '        If anl <> "" Then',
    '            anlTotal(anl) = anlTotal(anl) + 1: anlCompSum(anl) = anlCompSum(anl) + tickets(i).complexity',
    '            If tickets(i).final_grade = "ОТЛИЧНО" Then anlExc(anl) = anlExc(anl) + 1',
    '            If tickets(i).final_grade = "ХОРОШО" Then anlGood(anl) = anlGood(anl) + 1',
    '            If tickets(i).final_grade = "ПЛОХО" Then anlBad(anl) = anlBad(anl) + 1',
    '        End If',
    '    Next i',
    '    Dim emoAvg As Double: emoAvg = IIf(emoTotal > 0, Round(CDbl(emoSum) / emoTotal, 1), 0#)',
    '    Dim topInitHtml As String: topInitHtml = ""',
    '    Dim kCli As Variant, initRows As Long: initRows = 0',
    '    For Each kCli In initiatorCounts.Keys',
    '        initRows = initRows + 1: If initRows > TOP_INITIATORS_N Then Exit For',
    '        topInitHtml = topInitHtml & "<tr><td><b>" & kCli & "</b></td><td>" & initiatorCounts(kCli) & "</td><td>" & initiatorTopics(kCli) & "</td><td>-</td></tr>"',
    '    Next kCli',
    '    Dim topAnlHtml As String: topAnlHtml = ""',
    '    Dim nomHardAnl As String, nomQtyAnl As String, nomQualAnl As String',
    '    Dim maxScore As Double: maxScore = -9999, maxQty As Long: maxQty = 0',
    '    For Each kCli In anlTotal.Keys',
    '        Dim cTot As Long: cTot = anlTotal(kCli)',
    '        Dim cExc As Long: cExc = anlExc(kCli)',
    '        Dim cGood As Long: cGood = anlGood(kCli)',
    '        Dim cBad As Long: cBad = anlBad(kCli)',
    '        Dim avgCmp As Double: avgCmp = Round(CDbl(anlCompSum(kCli)) / cTot, 1)',
    '        Dim sc As Double: sc = Round((cExc * 3 + cGood * 1 - cBad * 3) * avgCmp, 1)',
    '        If cTot > maxQty Then maxQty = cTot: nomQtyAnl = CStr(kCli)',
    '        If sc > maxScore Then maxScore = sc: nomQualAnl = CStr(kCli)',
    '        topAnlHtml = topAnlHtml & "<tr><td><b>" & kCli & "</b></td><td>" & cTot & "</td><td>" & cExc & "</td><td>" & cGood & "</td><td>" & cBad & "</td><td>" & avgCmp & "</td><td><b>" & sc & "</b></td></tr>"',
    '    Next kCli',
    '    Dim pieJson As String: pieJson = "{"',
    '    Dim firstK As Boolean: firstK = True',
    '    For Each kCli In topicCounts.Keys',
    '        If Not firstK Then pieJson = pieJson & ","',
    '        pieJson = pieJson & """" & EscapeJSON(CStr(kCli)) & """:" & topicCounts(kCli): firstK = False',
    '    Next kCli',
    '    pieJson = pieJson & "}"',
    '    Dim h As String: h = tpl',
    '    h = Replace(h, "{{ week_header }}", "W" & maxWeek & " [" & minClsStr & "]")',
    '    h = Replace(h, "{{ total_tickets }}", CStr(totalCount))',
    '    h = Replace(h, "{{ med_hour }}", Format(medHour, "0.0"))',
    '    h = Replace(h, "{{ mid_hour }}", Format(midHour, "0.0"))',
    '    h = Replace(h, "{{ dates_reg }}", minRegStr & " — " & maxRegStr)',
    '    h = Replace(h, "{{ dates_cls }}", minClsStr & " — " & maxClsStr)',
    '    h = Replace(h, "{{ emo_total }}", CStr(emoTotal))',
    '    h = Replace(h, "{{ emo_avg }}", Format(emoAvg, "0.0"))',
    '    h = Replace(h, "{{ emo_max }}", CStr(emoMax))',
    '    h = Replace(h, "{{ alt_total }}", CStr(altTotal))',
    '    h = Replace(h, "{{ ai_conclusions | safe }}", aiConclusions)',
    '    h = Replace(h, "{{ tip_text }}", "Оптимизация 3 частых сбоев снижает нагрузку на 15%.")',
    '    h = Replace(h, "{{ pie_json | safe }}", pieJson)',
    '    h = Replace(h, "{{ batch_tokens }}", CStr(batchTokens))',
    '    h = Replace(h, "{{ summary_tokens }}", CStr(summaryTokens))',
    '    h = Replace(h, "{{ batch_model }}", BATCH_MODEL)',
    '    h = Replace(h, "{{ summary_model }}", SUMMARY_MODEL)',
    '    h = Replace(h, "{{ nom_hard_anl }}", IIf(nomHardAnl = "", "Н/Д", nomHardAnl))',
    '    h = Replace(h, "{{ nom_hard_txt }}", "Макс. сложность")',
    '    h = Replace(h, "{{ nom_qty_anl }}", IIf(nomQtyAnl = "", "Н/Д", nomQtyAnl))',
    '    h = Replace(h, "{{ nom_qty_txt }}", maxQty & " обращений")',
    '    h = Replace(h, "{{ nom_qual_anl }}", IIf(nomQualAnl = "", "Н/Д", nomQualAnl))',
    '    h = Replace(h, "{{ nom_qual_txt }}", "Балл: " & Format(maxScore, "0.0"))',
    '    h = ReplaceJinjaBlock(h, "{% for row in top_initiators %}", "{% endfor %}", topInitHtml)',
    '    h = ReplaceJinjaBlock(h, "{% for row in top_analysts %}", "{% endfor %}", topAnlHtml)',
    '    Set stm = CreateObject("ADODB.Stream"): stm.Type = 2: stm.Charset = "utf-8": stm.Open: stm.WriteText h: stm.SaveToFile outputPath, 2: stm.Close',
    'End Sub',
    '',
    'Private Function ReplaceJinjaBlock(ByVal content As String, ByVal startTag As String, ByVal endTag As String, ByVal replacement As String) As String',
    '    Dim p1 As Long, p2 As Long: p1 = InStr(content, startTag)',
    '    If p1 > 0 Then',
    '        p2 = InStr(p1, content, endTag)',
    '        If p2 > 0 Then ReplaceJinjaBlock = Left(content, p1 - 1) & replacement & Mid(content, p2 + Len(endTag)): Exit Function',
    '    End If',
    '    ReplaceJinjaBlock = content',
    'End Function'
)

Save-FileLines -Path "$root\src\Mod_Main.bas" -Lines @(
    'Attribute VB_Name = "Mod_Main"',
    'Option Explicit',
    '',
    'Public Sub RunSupportAnalytics()',
    '    On Error GoTo ErrHandler',
    '    Dim wb As Workbook: Set wb = ThisWorkbook',
    '    Dim wsSource As Worksheet',
    '    On Error Resume Next: Set wsSource = wb.Worksheets("Data")',
    '    If wsSource Is Nothing Then Set wsSource = wb.ActiveSheet',
    '    On Error GoTo ErrHandler',
    '    Dim lastRow As Long: lastRow = wsSource.Cells(wsSource.Rows.count, "A").End(xlUp).Row',
    '    If lastRow < 2 Then MsgBox "Таблица с данными пуста!", vbExclamation: Exit Sub',
    '    Application.StatusBar = "Чтение данных и расчет SLA...": Application.ScreenUpdating = False',
    '    Dim tickets() As TicketData: ReDim tickets(1 To lastRow - 1)',
    '    Dim validCount As Long: validCount = 0, r As Long',
    '    Dim maxYear As Long: maxYear = 0, maxWeek As Long: maxWeek = 0',
    '    Dim minRegDate As Date: minRegDate = DateSerial(2099, 1, 1), maxRegDate As Date: maxRegDate = DateSerial(1900, 1, 1)',
    '    Dim minClsDate As Date: minClsDate = DateSerial(2099, 1, 1), maxClsDate As Date: maxClsDate = DateSerial(1900, 1, 1)',
    '    For r = 2 To lastRow',
    '        Dim clsVal As String: clsVal = Trim(CStr(wsSource.Cells(r, 3).Value))',
    '        If clsVal <> "" And IsDate(clsVal) Then',
    '            validCount = validCount + 1',
    '            With tickets(validCount)',
    '                .id = CStr(wsSource.Cells(r, 1).Value): .reg = CStr(wsSource.Cells(r, 2).Value): .cls = clsVal',
    '                .cli = CStr(wsSource.Cells(r, 4).Value): .anl = CStr(wsSource.Cells(r, 5).Value)',
    '                .sec = CStr(wsSource.Cells(r, 6).Value): .desc = CStr(wsSource.Cells(r, 7).Value): .sol = CStr(wsSource.Cells(r, 8).Value)',
    '                .reg_dt = CDate(.reg): .cls_dt = CDate(.cls): .has_cls = True',
    '                .iso_year = GetISOYear(.cls_dt): .iso_week = GetISOWeek(.cls_dt): .dif_Hour = CalcBusHours(.reg_dt, .cls_dt)',
    '                If .iso_year > maxYear Then maxYear = .iso_year',
    '                If .iso_week > maxWeek Then maxWeek = .iso_week',
    '                If .reg_dt < minRegDate Then minRegDate = .reg_dt',
    '                If .reg_dt > maxRegDate Then maxRegDate = .reg_dt',
    '                If .cls_dt < minClsDate Then minClsDate = .cls_dt',
    '                If .cls_dt > maxClsDate Then maxClsDate = .cls_dt',
    '            End With',
    '        End If',
    '    Next r',
    '    If validCount = 0 Then MsgBox "Нет закрытых тикетов!", vbExclamation: Exit Sub',
    '    ReDim Preserve tickets(1 To validCount)',
    '    Dim totalBatchTok As Long: totalBatchTok = 0, batchIdx As Long, numBatches As Long',
    '    numBatches = Application.WorksheetFunction.RoundUp(validCount / BATCH_SIZE, 0)',
    '    For batchIdx = 1 To numBatches',
    '        Dim bStart As Long: bStart = (batchIdx - 1) * BATCH_SIZE + 1',
    '        Dim bEnd As Long: bEnd = batchIdx * BATCH_SIZE: If bEnd > validCount Then bEnd = validCount',
    '        Application.StatusBar = "Батч " & batchIdx & " из " & numBatches & "..."',
    '        Dim promptRows As String: promptRows = "", i As Long',
    '        For i = bStart To bEnd',
    '            promptRows = promptRows & "ID: " & tickets(i).id & " | Тема: " & tickets(i).sec & " | Описание: " & tickets(i).desc & vbCrLf',
    '        Next i',
    '        Dim pTok As Long, cTok As Long, tTok As Long',
    '        Dim jsonResp As String: jsonResp = CallGeminiBatch("Оцени:" & vbCrLf & promptRows, pTok, cTok, tTok)',
    '        totalBatchTok = totalBatchTok + tTok',
    '        Dim resObjects As Collection: Set resObjects = ExtractArrayObjects(jsonResp, "results")',
    '        Dim itemJson As Variant',
    '        For Each itemJson In resObjects',
    '            Dim tId As String: tId = ExtractJSONValue(CStr(itemJson), "id")',
    '            For i = bStart To bEnd',
    '                If tickets(i).id = tId Then',
    '                    tickets(i).topic_cluster = ExtractJSONValue(CStr(itemJson), "topic_cluster")',
    '                    tickets(i).tone_deviation_score = CLng(Val(ExtractJSONValue(CStr(itemJson), "tone_deviation_score")))',
    '                    tickets(i).complexity = CLng(Val(ExtractJSONValue(CStr(itemJson), "complexity")))',
    '                    tickets(i).final_grade = UCase(Trim(ExtractJSONValue(CStr(itemJson), "final_grade")))',
    '                    tickets(i).grade_argument = ExtractJSONValue(CStr(itemJson), "grade_argument")',
    '                    Exit For',
    '                End If',
    '            Next i',
    '        Next itemJson',
    '    Next batchIdx',
    '    Dim difArr() As Double: ReDim difArr(1 To validCount)',
    '    Dim totalDifHours As Double: totalDifHours = 0#',
    '    For i = 1 To validCount: difArr(i) = tickets(i).dif_Hour: totalDifHours = totalDifHours + tickets(i).dif_Hour: Next i',
    '    Dim medHour As Double: medHour = Round(CalcMedian(difArr, validCount), 1)',
    '    Dim midHour As Double: midHour = Round(totalDifHours / validCount, 1)',
    '    Application.StatusBar = "Генерация выводов Pro..."',
    '    Dim summaryTokens As Long: summaryTokens = 0',
    '    Dim aiConclusions As String: aiConclusions = CallGeminiSummary("Всего: " & validCount & ", Медиана: " & medHour, summaryTokens)',
    '    Dim runId As String: runId = Format(Now, "yyyymmdd_hhnnss")',
    '    LogResults wb, runId, maxYear, maxWeek, validCount, totalBatchTok, summaryTokens',
    '    Dim templatePath As String: templatePath = wb.Path & "\template.html"',
    '    Dim outputPath As String: outputPath = wb.Path & "\Отчет по качеству W" & maxWeek & ".html"',
    '    GenerateHtmlReport templatePath, outputPath, tickets, validCount, maxYear, maxWeek, _',
    '                       Format(minRegDate, "dd.mm.yyyy"), Format(maxRegDate, "dd.mm.yyyy"), _',
    '                       Format(minClsDate, "dd.mm.yyyy"), Format(maxClsDate, "dd.mm.yyyy"), _',
    '                       medHour, midHour, aiConclusions, totalBatchTok, summaryTokens',
    '    Application.StatusBar = False: Application.ScreenUpdating = True',
    '    MsgBox "Готово! Отчет: " & outputPath, vbInformation',
    '    Exit Sub',
    'ErrHandler:',
    '    Application.StatusBar = False: Application.ScreenUpdating = True',
    '    MsgBox "Ошибка: " & Err.Description, vbCritical',
    'End Sub',
    '',
    'Private Sub LogResults(ByVal wb As Workbook, ByVal runId As String, ByVal y As Long, ByVal w As Long, ByVal total As Long, ByVal bTok As Long, ByVal sTok As Long)',
    '    Dim wsLogs As Worksheet, wsTokens As Worksheet',
    '    On Error Resume Next: Set wsLogs = wb.Worksheets("Logs"): On Error GoTo 0',
    '    If wsLogs Is Nothing Then',
    '        Set wsLogs = wb.Worksheets.Add(After:=wb.Worksheets(wb.Worksheets.count)): wsLogs.name = "Logs"',
    '        wsLogs.Range("A1:F1").Value = Array("Run_ID", "Timestamp", "Year", "Week", "Total_Tickets", "Status")',
    '    End If',
    '    Dim nextR As Long: nextR = wsLogs.Cells(wsLogs.Rows.count, "A").End(xlUp).Row + 1',
    '    wsLogs.Cells(nextR, 1).Resize(1, 6).Value = Array(runId, Format(Now, "yyyy-mm-dd hh:nn:ss"), y, w, total, "SUCCESS")',
    '    On Error Resume Next: Set wsTokens = wb.Worksheets("Token"): On Error GoTo 0',
    '    If wsTokens Is Nothing Then',
    '        Set wsTokens = wb.Worksheets.Add(After:=wb.Worksheets(wb.Worksheets.count)): wsTokens.name = "Token"',
    '        wsTokens.Range("A1:E1").Value = Array("Run_ID", "Batch_Model", "Batch_Tokens", "Summary_Model", "Summary_Tokens")',
    '    End If',
    '    nextR = wsTokens.Cells(wsTokens.Rows.count, "A").End(xlUp).Row + 1',
    '    wsTokens.Cells(nextR, 1).Resize(1, 5).Value = Array(runId, BATCH_MODEL, bTok, SUMMARY_MODEL, sTok)',
    'End Sub'
)

Write-Host "`n🎉 Развертывание завершено успешно!" -ForegroundColor Green
Write-Host "👉 Нажмите Ctrl + Shift + B в VS Code для сборки в Workbook.xlsm." -ForegroundColor Yellow